oro_jobs:
    label: oro.cron.action.jobs_management
    type: action
    group_name: ""
    bindings: ~

oro_schedules:
    label: oro.cron.action.schedules
    type: action
    group_name: ""
    bindings: ~
