parameters:
    oro_cron.job_daemon.class:        Oro\Bundle\CronBundle\Job\Daemon
    oro_cron.job_manager.class:       Oro\Bundle\CronBundle\Entity\Manager\JobManager
    oro_cron.jms_job_helper.class:    Oro\Bundle\CronBundle\Helper\JmsJobHelper

services:
    oro_cron.job_daemon:
        class:                        %oro_cron.job_daemon.class%
        arguments:
            - %kernel.root_dir%
            - %oro_cron.max_jobs%
            - %oro_cron.max_runtime%
            - %kernel.environment%

    oro_cron.job_manager:
        class:                        %oro_cron.job_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    oro_cron.jms_job_helper:
        class: %oro_cron.jms_job_helper.class%
        arguments:
            - @doctrine