parameters:
    oro_cron.job_daemon.class:        Oro\Bundle\CronBundle\Job\Daemon
    oro_cron.job_manager.class:       Oro\Bundle\CronBundle\Entity\Manager\JobManager
    oro_cron.command_with_args_string_filter.class: Oro\Bundle\CronBundle\Filter\CommandWithArgsFilter

services:
    oro_cron.job_daemon:
        class:                        %oro_cron.job_daemon.class%
        arguments:
            - %kernel.root_dir%
            - %oro_cron.max_jobs%
            - %oro_cron.max_runtime%
            - %kernel.environment%

    oro_cron.job_manager:
        class:                        %oro_cron.job_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"

    oro_cron.command_with_args_string_filter:
        class: %oro_cron.command_with_args_string_filter.class%
        arguments:
            - @form.factory
            - @oro_filter.filter_utility
        tags:
            - { name: oro_filter.extension.orm_filter.filter, type: command_with_args }