parameters:
    oro_cron.job_daemon.class:        Oro\Bundle\CronBundle\Job\Daemon

services:
    oro_cron.job_daemon:
        class:                        %oro_cron.job_daemon.class%
        arguments:                    [%kernel.root_dir%, %oro_cron.max_jobs%]
