bundles:
    - JMS\JobQueueBundle\JMSJobQueueBundle
    - Oro\Bundle\CronBundle\OroCronBundle
bundleAliases:
    JMS\JobQueueBundle\JMSJobQueueBundle: Oro\Bundle\CronBundle\JMSJobQueueBundle\JMSJobQueueBundle